version: '3'

services:
  reverse-proxy:
    image: traefik:latest
    container_name: reverse-proxy
    restart: always
    security_opt:
      - label=type:container_runtime_t
    ports:
      - 9100:80
      - 9101:443
      - 9102:8080
    volumes:
      - /run/user/1001/podman/podman.sock:/var/run/docker.sock:z
    command:
      - "--api.insecure=true"
      - --providers.docker=true
      - "--entrypoints.web.address=:80"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"