name: vscode
services:
    codeserver:
        container_name: vscodeserver
        ports:
            - ${VSCODE_PORT}:8443
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - PASSWORD=${VSCODE_PASSWORD}
            - DEFAULT_WORKSPACE=${DEFAULT_WORKSPACE}
        volumes:
            - ${DOCKER_VOLUME_BASE}/codeserver:/config
            - ${DOCKER_VOLUME_BASE}/codeserver/data:/data
            - ${DOCKER_VOLUME_BASE}:/repos
        restart: unless-stopped
        image: lscr.io/linuxserver/code-server:latest
