version: "3.8"

services:
  glance:
    image: glanceapp/glance # Uses the official Glance Docker image.
    container_name: glance # Assigns a custom container name for easy management.
    volumes:
      - ./home.yaml:/app/glance.yml # Mounts the home.yaml configuration file.
      - /etc/timezone:/etc/timezone:ro # Ensures container timezone sync.
      - /etc/localtime:/etc/localtime:ro # Ensures container localtime sync.
    ports:
      - ${GLANCE_PORT}:8080 # Exposes Glance on port 8280.
    restart: unless-stopped # Restarts container unless manually stopped.
