name = "Security"

[[data]]
name = "AppArmor GRUB Setup"
description = "Configures GRUB to enable AppArmor and related security settings."
script = "apparmor-grub-setup.sh"
task_list = "I"

[[data]]
name = "FirewallD Firewall Baselines (CTT)"
description = "Configure FirewallD with CTT's recommended baseline rules for improved system security. For more information visit: https://christitus.com/linux-security-mistakes"
script = "firewalld-baselines.sh"
task_list = "I SS"

[[data.preconditions]]
matches = true
data = "command_exists"
values = [ "firewall-cmd" ]
[[data]]
name = "Sunshine Port Forward"
description = "Configures port forwarding for Sunshine game streaming."
script = "sunshine-portfwd.sh"
task_list = "PFM"

[[data]]
name = "UFW Firewall Baselines (CTT)"
description = "Developed to ease iptables firewall configuration, UFW provides a user friendly way to create an IPv4 or IPv6 host-based firewall. This command installs UFW and configures UFW based on CTT's recommended rules. For more information visit: https://christitus.com/linux-security-mistakes"
script = "ufw-baselines.sh"
task_list = "I SS"

[[data.preconditions]]
matches = false
data = "command_exists"
values = [ "firewall-cmd" ]

[[data]]
name = "YubiKey PAM"
description = "Configures YubiKey PAM authentication."
script = "yk-pam.sh"
task_list = "I"

