name: anythingllm
services:
  anythingllm:
    ports:
      - ${SERVER_PORT}:3001
    cap_add:
      - SYS_ADMIN
    volumes:
      - ${STORAGE_DIR}:/app/server/storage
      - ${STORAGE_DIR}/.env:/app/server/.env
    environment:
      - STORAGE_DIR=${STORAGE_DIR}
      - UID=${UID}
      - GID=${GID}
    image: mintplexlabs/anythingllm
