name: vaultwarden
services:
    \:
        container_name: vaultwarden
        environment:
            - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED}
            - SIGNUPS_DOMAINS_WHITELIST=${SIGNUPS_DOMAINS_WHITELIST}
        volumes:
            - ${DOCKER_VOLUME_BASE}/vaultwarden:/data
        ports:
            - ${VAULTWARDEN_PORT}:80
        restart: unless-stopped
        image: \
